//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WndView {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsForm() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WndView.SettingsForm", typeof(SettingsForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 [Font: Name=Times New Roman, Size=14.25, Units=3, GdiCharSet=1, GdiVerticalFont=False] 的類型 System.Drawing.Font 當地語系化資源。
        /// </summary>
        public static System.Drawing.Font groupBox1_Font {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=12,Y=12} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        public static System.Drawing.Point groupBox1_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=301, Height=170} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        public static System.Drawing.Size groupBox1_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 6 的類型 System.Int32 當地語系化資源。
        /// </summary>
        public static int groupBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Global Hotkeys 的當地語系化字串。
        /// </summary>
        public static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [Font: Name=Times New Roman, Size=9.75, Units=3, GdiCharSet=1, GdiVerticalFont=False] 的類型 System.Drawing.Font 當地語系化資源。
        /// </summary>
        public static System.Drawing.Font SetKey_ClickThrough_Font {
            get {
                object obj = ResourceManager.GetObject("SetKey_ClickThrough.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=120,Y=30} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        public static System.Drawing.Point SetKey_ClickThrough_Location {
            get {
                object obj = ResourceManager.GetObject("SetKey_ClickThrough.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=150, Height=25} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        public static System.Drawing.Size SetKey_ClickThrough_Size {
            get {
                object obj = ResourceManager.GetObject("SetKey_ClickThrough.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 3 的類型 System.Int32 當地語系化資源。
        /// </summary>
        public static int SetKey_ClickThrough_TabIndex {
            get {
                object obj = ResourceManager.GetObject("SetKey_ClickThrough.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 label1 的當地語系化字串。
        /// </summary>
        public static string SetKey_ClickThrough_Text {
            get {
                return ResourceManager.GetString("SetKey_ClickThrough.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MiddleCenter 的類型 System.Drawing.ContentAlignment 當地語系化資源。
        /// </summary>
        public static System.Drawing.ContentAlignment SetKey_ClickThrough_TextAlign {
            get {
                object obj = ResourceManager.GetObject("SetKey_ClickThrough.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 [Font: Name=Times New Roman, Size=9.75, Units=3, GdiCharSet=1, GdiVerticalFont=False] 的類型 System.Drawing.Font 當地語系化資源。
        /// </summary>
        public static System.Drawing.Font SetKey_Exit_Font {
            get {
                object obj = ResourceManager.GetObject("SetKey_Exit.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=120,Y=126} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        public static System.Drawing.Point SetKey_Exit_Location {
            get {
                object obj = ResourceManager.GetObject("SetKey_Exit.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=150, Height=25} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        public static System.Drawing.Size SetKey_Exit_Size {
            get {
                object obj = ResourceManager.GetObject("SetKey_Exit.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 12 的類型 System.Int32 當地語系化資源。
        /// </summary>
        public static int SetKey_Exit_TabIndex {
            get {
                object obj = ResourceManager.GetObject("SetKey_Exit.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 label6 的當地語系化字串。
        /// </summary>
        public static string SetKey_Exit_Text {
            get {
                return ResourceManager.GetString("SetKey_Exit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MiddleCenter 的類型 System.Drawing.ContentAlignment 當地語系化資源。
        /// </summary>
        public static System.Drawing.ContentAlignment SetKey_Exit_TextAlign {
            get {
                object obj = ResourceManager.GetObject("SetKey_Exit.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 [Font: Name=Times New Roman, Size=9.75, Units=3, GdiCharSet=1, GdiVerticalFont=False] 的類型 System.Drawing.Font 當地語系化資源。
        /// </summary>
        public static System.Drawing.Font SetKey_Hide_Font {
            get {
                object obj = ResourceManager.GetObject("SetKey_Hide.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=120,Y=94} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        public static System.Drawing.Point SetKey_Hide_Location {
            get {
                object obj = ResourceManager.GetObject("SetKey_Hide.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=150, Height=25} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        public static System.Drawing.Size SetKey_Hide_Size {
            get {
                object obj = ResourceManager.GetObject("SetKey_Hide.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 10 的類型 System.Int32 當地語系化資源。
        /// </summary>
        public static int SetKey_Hide_TabIndex {
            get {
                object obj = ResourceManager.GetObject("SetKey_Hide.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 label6 的當地語系化字串。
        /// </summary>
        public static string SetKey_Hide_Text {
            get {
                return ResourceManager.GetString("SetKey_Hide.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MiddleCenter 的類型 System.Drawing.ContentAlignment 當地語系化資源。
        /// </summary>
        public static System.Drawing.ContentAlignment SetKey_Hide_TextAlign {
            get {
                object obj = ResourceManager.GetObject("SetKey_Hide.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 [Font: Name=Times New Roman, Size=9.75, Units=3, GdiCharSet=1, GdiVerticalFont=False] 的類型 System.Drawing.Font 當地語系化資源。
        /// </summary>
        public static System.Drawing.Font SetKey_Show_Font {
            get {
                object obj = ResourceManager.GetObject("SetKey_Show.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=120,Y=62} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        public static System.Drawing.Point SetKey_Show_Location {
            get {
                object obj = ResourceManager.GetObject("SetKey_Show.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=150, Height=25} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        public static System.Drawing.Size SetKey_Show_Size {
            get {
                object obj = ResourceManager.GetObject("SetKey_Show.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 6 的類型 System.Int32 當地語系化資源。
        /// </summary>
        public static int SetKey_Show_TabIndex {
            get {
                object obj = ResourceManager.GetObject("SetKey_Show.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 label4 的當地語系化字串。
        /// </summary>
        public static string SetKey_Show_Text {
            get {
                return ResourceManager.GetString("SetKey_Show.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MiddleCenter 的類型 System.Drawing.ContentAlignment 當地語系化資源。
        /// </summary>
        public static System.Drawing.ContentAlignment SetKey_Show_TextAlign {
            get {
                object obj = ResourceManager.GetObject("SetKey_Show.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Press Keys... 的當地語系化字串。
        /// </summary>
        public static string SetKeyLabelText {
            get {
                return ResourceManager.GetString("SetKeyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [Font: Name=Times New Roman, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False] 的類型 System.Drawing.Font 當地語系化資源。
        /// </summary>
        public static System.Drawing.Font SetKeyName_ClickThrough_Font {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_ClickThrough.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=9,Y=31} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        public static System.Drawing.Point SetKeyName_ClickThrough_Location {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_ClickThrough.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=6,Top=6,Right=3,Bottom=6} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        public static System.Windows.Forms.Padding SetKeyName_ClickThrough_Margin {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_ClickThrough.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=105, Height=20} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        public static System.Drawing.Size SetKeyName_ClickThrough_Size {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_ClickThrough.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 1 的類型 System.Int32 當地語系化資源。
        /// </summary>
        public static int SetKeyName_ClickThrough_TabIndex {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_ClickThrough.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Click Through : 的當地語系化字串。
        /// </summary>
        public static string SetKeyName_ClickThrough_Text {
            get {
                return ResourceManager.GetString("SetKeyName_ClickThrough.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MiddleRight 的類型 System.Drawing.ContentAlignment 當地語系化資源。
        /// </summary>
        public static System.Drawing.ContentAlignment SetKeyName_ClickThrough_TextAlign {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_ClickThrough.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 [Font: Name=Times New Roman, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False] 的類型 System.Drawing.Font 當地語系化資源。
        /// </summary>
        public static System.Drawing.Font SetKeyName_Exit_Font {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Exit.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=9,Y=127} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        public static System.Drawing.Point SetKeyName_Exit_Location {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Exit.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=6,Top=6,Right=3,Bottom=6} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        public static System.Windows.Forms.Padding SetKeyName_Exit_Margin {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Exit.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=105, Height=20} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        public static System.Drawing.Size SetKeyName_Exit_Size {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Exit.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 11 的類型 System.Int32 當地語系化資源。
        /// </summary>
        public static int SetKeyName_Exit_TabIndex {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Exit.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Exit : 的當地語系化字串。
        /// </summary>
        public static string SetKeyName_Exit_Text {
            get {
                return ResourceManager.GetString("SetKeyName_Exit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MiddleRight 的類型 System.Drawing.ContentAlignment 當地語系化資源。
        /// </summary>
        public static System.Drawing.ContentAlignment SetKeyName_Exit_TextAlign {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Exit.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 [Font: Name=Times New Roman, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False] 的類型 System.Drawing.Font 當地語系化資源。
        /// </summary>
        public static System.Drawing.Font SetKeyName_Hide_Font {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Hide.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=9,Y=95} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        public static System.Drawing.Point SetKeyName_Hide_Location {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Hide.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=6,Top=6,Right=3,Bottom=6} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        public static System.Windows.Forms.Padding SetKeyName_Hide_Margin {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Hide.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=105, Height=20} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        public static System.Drawing.Size SetKeyName_Hide_Size {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Hide.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 9 的類型 System.Int32 當地語系化資源。
        /// </summary>
        public static int SetKeyName_Hide_TabIndex {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Hide.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Hide : 的當地語系化字串。
        /// </summary>
        public static string SetKeyName_Hide_Text {
            get {
                return ResourceManager.GetString("SetKeyName_Hide.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MiddleRight 的類型 System.Drawing.ContentAlignment 當地語系化資源。
        /// </summary>
        public static System.Drawing.ContentAlignment SetKeyName_Hide_TextAlign {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Hide.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 [Font: Name=Times New Roman, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False] 的類型 System.Drawing.Font 當地語系化資源。
        /// </summary>
        public static System.Drawing.Font SetKeyName_Show_Font {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Show.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=9,Y=63} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        public static System.Drawing.Point SetKeyName_Show_Location {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Show.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=6,Top=6,Right=3,Bottom=6} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        public static System.Windows.Forms.Padding SetKeyName_Show_Margin {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Show.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=105, Height=20} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        public static System.Drawing.Size SetKeyName_Show_Size {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Show.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 5 的類型 System.Int32 當地語系化資源。
        /// </summary>
        public static int SetKeyName_Show_TabIndex {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Show.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Show : 的當地語系化字串。
        /// </summary>
        public static string SetKeyName_Show_Text {
            get {
                return ResourceManager.GetString("SetKeyName_Show.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MiddleRight 的類型 System.Drawing.ContentAlignment 當地語系化資源。
        /// </summary>
        public static System.Drawing.ContentAlignment SetKeyName_Show_TextAlign {
            get {
                object obj = ResourceManager.GetObject("SetKeyName_Show.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=159,Y=357} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        public static System.Drawing.Point SettingBtn_Cancel_Location {
            get {
                object obj = ResourceManager.GetObject("SettingBtn_Cancel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=75, Height=23} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        public static System.Drawing.Size SettingBtn_Cancel_Size {
            get {
                object obj = ResourceManager.GetObject("SettingBtn_Cancel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 2 的類型 System.Int32 當地語系化資源。
        /// </summary>
        public static int SettingBtn_Cancel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("SettingBtn_Cancel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string SettingBtn_Cancel_Text {
            get {
                return ResourceManager.GetString("SettingBtn_Cancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=78,Y=357} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        public static System.Drawing.Point SettingBtn_OK_Location {
            get {
                object obj = ResourceManager.GetObject("SettingBtn_OK.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=75, Height=23} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        public static System.Drawing.Size SettingBtn_OK_Size {
            get {
                object obj = ResourceManager.GetObject("SettingBtn_OK.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的類型 System.Int32 當地語系化資源。
        /// </summary>
        public static int SettingBtn_OK_TabIndex {
            get {
                object obj = ResourceManager.GetObject("SettingBtn_OK.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        public static string SettingBtn_OK_Text {
            get {
                return ResourceManager.GetString("SettingBtn_OK.Text", resourceCulture);
            }
        }
    }
}
